### ISSUE TITLE
Build Markdown Document?

### ISSUE THREAD

**Issue by dakl** [sjosund/ml-project-checklist#2]
Hello! Thanks for a great list. Would it be possible to build a markdown with checkboxes for easy copy-paste to git repos? I'd like to not maintain my own version for that :)

**Comment by sjosund** [comment]
Hi @dakl ! Great idea - I was initially using markdown for the list, but couldn't get magicbook to work properly with it. I'll have a look at it again and will keep you updated.

**Comment by sjosund** [comment]
I've added the markdown list as the README file. I'll go ahead and close this issue.

**Comment by dakl** [comment]
Awesome, thanks!
